# Generated by Django 5.1.7 on 2025-03-27 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('school_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='default.jpeg', upload_to='logos')),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['school_name'], name='SchoolsAuth_school__27f364_idx'), models.Index(fields=['school_id'], name='SchoolsAuth_school__79879e_idx')],
            },
        ),
    ]
